### ISSUE TITLE
SWIM support

### ISSUE THREAD

**Issue by lalten** [myelin/arduino-cmsis-dap#3]
I wanted to flash a 4.12 VESC motor controller, which apparently needs SWIM.

Any chance you could add this feature?

**Comment by myelin** [comment]
I'd never heard of SWIM before -- very interesting!  Looks like it's specified here: https://www.st.com/content/ccc/resource/technical/document/user_manual/ca/89/41/4e/72/31/49/f4/CD00173911.pdf/files/CD00173911.pdf/jcr:content/translations/en.CD00173911.pdf

Unless SWIM is supported by later versions of CMSIS-DAP, I think that's out of scope for this project, so I'm going to close this issue as "won't fix" :)

It looks like the best way to hack one together is to flash the STLinkV2 firmware to an STM32 board.  Here's a DIY solution -- http://stm32duino.com/viewtopic.php?t=2954

Here's one from Adafruit -- https://www.adafruit.com/product/2548 -- and I'm pretty sure you can get those for $2 if you search for "st-link v2" on Aliexpress.
